### ISSUE TITLE
sc.pp.normalize_per_cell(adata)

### ISSUE THREAD

**Issue by handesome** [sldyns/scAce#2]
hi!
thanks for developing the wonderful algorithm!!
when I run the tutorial `sc.pp.normalize_per_cell(adata)`,
the error occur`UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'`,
when I change the code to`sc.pp.normalize_total(adata)`,comes another error`AttributeError: 'DataFrame' object has no attribute 'n_counts'`.
could you give some advice?Thanks!!!

**Comment by sldyns** [comment]
Hi!

I apologize for not encountering the error you mentioned earlier. My hunch is that it might be related to the version of the scanpy package you are using. Would you mind updating your package to the latest version and giving it another try?

**Comment by handesome** [comment]
Hi!
Thank you for the quick reply!!I create a new environment and it works. Could you please tell me how does enhancement
&nbsp;of an existing clustering result work? Could you give an example? Thanks again!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sldyns/scAce"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sldyns/scAce] sc.pp.normalize_per_cell(adata) (Issue #2)





 
Hi!
 
I apologize for not encountering the error you mentioned earlier. My hunch is that it might be related to the version of the scanpy package you are using. Would you mind updating your package to the latest version and giving it another try?

**Comment by sldyns** [comment]
Hi,

That's a great new!

For clustering enhancement, you can supply pre-clustering results as `y_pred_init` when using the `run_scace` function by setting `init_cluster=y_pred_init`.

For specific examples, please refer to our [reproducibility codes](https://github.com/sldyns/scAce/tree/main/reproducibility/Splitting)
